try{
  let a = 2+ b ;
} catch (e){
  console.log(e);
}finally{
  console.log("deu certo?");
}

console.log("Teste");


//Solta uma mensagem de erro no lugar do codigo errado sem parar o codigo inteiro 
//diferente do "debugger"
//